### ISSUE TITLE
парні індекси

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-array#1]
https://github.com/DenisPitsul/js-array/blob/4793ed03404ca68251687d80a444fd32986a31ee/assets/js/task1-5.js#L19-L20
- щоб не робити перевірок, можна індекс одразу на 2 нарощувати

**Comment by DenisPitsul** [comment]
Updated in commit:
https://github.com/DenisPitsul/js-array/commit/fb9298c523238cea10928a6e2e83ca48ba3916e6
